language: java
sudo: false

install:
  -

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "DPkkV1OEWmOaQcdauSlo8HN2SeCxiagY+5OcRxTj361P6nezRIiU1/0GYKuQIOdNIDvVbZ2C7fTuoXNJTDLTqLn1UUvRr5IPaBE1EG+oiPxeRGBgnFlh9c+rQzc/hBDzXk19uctXljNaFO9ZQo2eVvwKITMWzGk33BXOxOlZll8="

addons:
  coverity_scan:
    project:
      name: "mkordas/checkstyle"
      description: "Desc"
    notification_email: kontakt@michalkordas.com
    build_command_prepend: ""
    build_command:   "mvn compile"
    branch_pattern: master

cache:
  directories:
  - ~/.m2

branches:
  only:
    - master
