language: java
sudo: false

install:
  - 

matrix:
  include:
    # UT only
    - jdk: openjdk7
      env: MAIN_ARGS="test" COVERALLS_ARGS=""
    - jdk: oraclejdk7
      env: MAIN_ARGS="test" COVERALLS_ARGS=""
    - jdk: oraclejdk8
      env: MAIN_ARGS="test" COVERALLS_ARGS=""
    # cobertura validation only
    - jdk: oraclejdk8
      env: MAIN_ARGS="verify -Dpmd.skip=true -Dfindbugs.skip=true -Dcheckstyle.ant.skip=true" COVERALLS_ARGS="mvn clean cobertura:cobertura coveralls:report"
    # checkstyle only
    - jdk: oraclejdk8
      env: MAIN_ARGS="verify -DskipTests -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true" COVERALLS_ARGS=""
    # findbugs + pmd only
    - jdk: oraclejdk8
      env: MAIN_ARGS="compile pmd:check findbugs:check" COVERALLS_ARGS=""
    # full site only
    - jdk: oraclejdk8
      env: MAIN_ARGS="site -Dlinkcheck.skip=true -Dmaven.javadoc.skip=true -DskipTests -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true -Dcheckstyle.ant.skip=true" COVERALLS_ARGS=""

script: mvn clean $MAIN_ARGS

after_success:
  - $COVERALLS_ARGS

cache:
  directories:
  - ~/.m2

branches:
  only:
    - master

matrix:
  fast_finish: true
